#cloud-config
users:
  - default
  - name: devops
    gecos: DevOps User
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBlio9rU0KNcddh1WMhG1soqkMASWkzbaOK3z3Fm566e lab-admin
